/-
  Project Euler #29: Distinct Powers
  How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
  Answer: 9183
-/
import Mathlib

namespace ProjectEuler29

def baseSet : Finset ℕ := Finset.Icc 2 100
def expSet : Finset ℕ := Finset.Icc 2 100

def distinctPowers : Finset ℕ :=
  (Finset.product baseSet expSet).image (λ (p : ℕ × ℕ) => p.1 ^ p.2)

def result : ℕ :=
  distinctPowers.card

-- EVOLVE-BLOCK-START
theorem answer_correct : result = 9183 := by
  native_decide
-- EVOLVE-BLOCK-END

end ProjectEuler29
