import Mathlib

/-!
# Project Euler Problem 12: Highly Divisible Triangular Number

The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.

What is the value of the first triangle number to have over five hundred divisors?

Answer: 76576500
-/
namespace ProjectEuler12

/-- The n-th triangular number: T_n = n*(n+1)/2. -/
def triangular (n : ℕ) : ℕ :=
  n * (n + 1) / 2

/-- Number of divisors of n. -/
def divisor_count (n : ℕ) : ℕ :=
  ((Finset.Icc 1 n).filter (λ d => d ∣ n)).card

theorem answer_correct : triangular 12375 = 76576500 ∧ 500 < divisor_count (triangular 12375) ∧
    ∀ n, n < 12375 → divisor_count (triangular n) ≤ 500 := by
  -- EVOLVE-BLOCK-START
  native_decide
  -- EVOLVE-BLOCK-END

end ProjectEuler12
