import Mathlib

/-!
# Project Euler Problem 2: Even Fibonacci Numbers

Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.

Answer: 4613732
-/
namespace ProjectEuler2

/-- Sum of even Fibonacci numbers ≤ 4,000,000 (fuel-based iterative). -/
def sum_even_fib : ℕ :=
  let rec go (a b fuel : ℕ) : ℕ :=
    if fuel = 0 then 0
    else if a > 4000000 then 0
    else
      let tail := go b (a + b) (fuel - 1)
      if a % 2 = 0 then a + tail else tail
  termination_by fuel
  go 1 2 100

theorem answer_correct : sum_even_fib = 4613732 := by
  -- EVOLVE-BLOCK-START
  native_decide
  -- EVOLVE-BLOCK-END

end ProjectEuler2
