/-
  Project Euler #27: Quadratic Primes
  Find the product a * b of coefficients |a| < 1000, |b| ≤ 1000 for which n² + a*n + b
  produces the maximum number of consecutive primes starting at n = 0.
  Answer: -59231
-/
import Mathlib

namespace ProjectEuler27

-- Count consecutive primes generated by n² + a*n + b starting at n = 0
def countPrimes (a b : ℤ) : ℕ :=
  go 0
where
  go (n : ℕ) : ℕ :=
    if n ≥ 100 then 0
    else
      let v : ℤ := (n : ℤ) ^ 2 + a * (n : ℤ) + b
      if v > 0 ∧ Nat.Prime (v.natAbs) then 1 + go (n+1)
      else 0
    termination_by 100 - n

private def aFromN (n : ℕ) : ℤ := (n : ℤ) - 999
private def bFromM (m : ℕ) : ℤ := (m : ℤ) + 2

def result : ℤ :=
  goA 0 0 0
where
  goA (na : ℕ) (bestCount bestProd : ℤ) : ℤ :=
    if na ≥ 1999 then bestProd
    else
      let a := aFromN na
      let (newCount, newProd) := goB 0 a bestCount bestProd
      goA (na + 1) newCount newProd
    termination_by 1999 - na
  goB (nb : ℕ) (a : ℤ) (bestCount bestProd : ℤ) : ℤ × ℤ :=
    if nb ≥ 999 then (bestCount, bestProd)
    else
      let b := bFromM nb
      let c := (countPrimes a b : ℤ)
      if c > bestCount then goB (nb + 1) a c (a * b)
      else goB (nb + 1) a bestCount bestProd
    termination_by 999 - nb

-- EVOLVE-BLOCK-START
theorem answer_correct : result = (-59231 : ℤ) := by
  native_decide
-- EVOLVE-BLOCK-END

end ProjectEuler27
